export const SELECTION_SECTION_SHOW = 'SELECTION_SECTION_SHOW';
export const SELECT_ALL_BEDS = 'SELECT_ALL_BEDS';
export const SHOW_MODAL_SAVE_SELECT_BEDS = 'SHOW_MODAL_SAVE_SELECT_BEDS';
export const SET_LANGUEGE = 'SET_LANGUEGE';
export const SHOW_LOADING = 'SHOW_LOADING';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_USER_NAME = 'SET_USER_NAME';
export const ACTIVE_QR_LOGIN = 'ACTIVE_QR_LOGIN';
