import EStyleSheet from 'react-native-extended-stylesheet';
import {ImageBackground, View, Dimensions, Text} from 'react-native';
import fonts from '../../../utils/common/fonts';

import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

const {width, height} = Dimensions.get('window');

export const detailesRequest = EStyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  containerRequetInfo: {
    flex: 6,
    borderBottomColor: '$colorBorder',
    borderLeftColor: '$colorWhite',
    borderRightColor: '$colorWhite',
    borderTopColor: '$colorWhite',
    alignItems: 'center',
    borderWidth: 1,
  },
  containerImage: {
    width: width > 650 ? 350 : 200,
    height: width > 650 ? 350 : 200,
    shadowColor: '$colorBack',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 12,
    backgroundColor: '$colorIconFarbe',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    marginTop: 30,
    borderRadius: 300,
  },
  containerRejectRequest: {
    width: width > 650 ? 350 : 200,
    height: width > 650 ? 350 : 200,
    height: 200,
    shadowColor: '$colorBack',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 12,
    backgroundColor: '$colorFarbe1',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    marginTop: 30,
    borderRadius: 300,
  },
  containerAcceptRequest: {
    width: width > 650 ? 350 : 200,
    height: '100%',
    backgroundColor: '$colorWhite',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    marginTop: 30,
    borderRadius: 300,
    position: 'absolute',
    zIndex: 10,
  },
  containerAction: {
    flex: 3,
    justifyContent: 'center',
    alignItems: 'center',
  },
  containerLabels: {
    justifyContent: 'flex-end',
    flex: 2,
    paddingLeft: 60,
    width: '100%',
  },
  containerTime: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    paddingRight: 30,
    paddingBottom: 10,
    width: '100%',
  },
  timeStyle: {
    fontSize: 16,
    fontFamily: fonts.fontMain,
    color: '$colorMinutenFarbe',
  },
  labelStyle: {
    fontSize: 25,
    fontWeight: 'bold',
    fontFamily: fonts.fontMain,
  },
  subLabelStyle: {
    fontSize: 22,
    fontFamily: fonts.fontMain,
  },
  buttonStyles: {
    height: hp('7%'),
    width: '80%',
    borderWidth: 1,
    marginTop: 8,
    shadowColor: '$colorBack',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 5,
    borderColor: '$colorBorder',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },

  buttonStylesAndroid: {
    height: hp('7%'),
    width: '80%',
    borderWidth: 1,
    marginTop: 8,
    shadowColor: '$colorBack',
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 2,
    borderColor: '$colorBorder',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  unActiveButtonStyles: {
    height: hp('7%'),
    width: '80%',
    borderWidth: 1,
    marginTop: 8,
    shadowColor: '$colorBack',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 5,
    borderColor: '$colorBorder',
    backgroundColor: '$colorUnActive',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  activeButtonStyles: {
    height: hp('%'),
    width: '80%',
    borderWidth: 2,
    marginTop: 8,
    elevation: 5,
    shadowColor: '$colorBack',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    borderColor: '$colorUnActiveBorder',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  containerIconButton: {
    width: 25,
    height: 25,
    position: 'absolute',
    top: '2%',
    right: '2%',
    borderWidth: 0.3,
    borderColor: '$colorBorder',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 1.5,
    shadowColor: '$colorBack',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
  },
  labelButton: {
    fontSize: 17,
    fontFamily: fonts.fontMain,
  },
});
