require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.3'

target 'helpchat' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'RNLocalize', :path => '../node_modules/react-native-localize'
  
   
  pod 'SDWebImage', '~> 5.0'
  pod 'SDWebImageSVGKitPlugin'
  

  
  
  
#  pod 'PocketSVG', '~> 2.6'


  


  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  

  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

  target 'helpchatTests' do
    inherit! :complete
    # Pods for testing
  end
  
  
 

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end

target 'helpchat-tvOS' do
  # Pods for helpchat-tvOS

  target 'helpchat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 3.0', '< 4.0'
end

