export const restApi = {
  GET_ALL_REQUEST: '/api/all_requests',
  GET_MY_REQUEST: '/api/my_requests',
  ACCEPT_ORDERS: '/api/request',
  API_LOGIN: '/oauth/token',
  API_SEND_CODE: '/api/forgot/code',
  API_VERIFY_CODE: '/api/forgot/verify',
  API_CHANGE_PASSWORD: '/api/forgot/update',
  API_ATTENDANCE: '/api/attendance',
  GET_BEDS_LIST: '/api/room',
  GET_ROOM_LIST: '/api/room',
  GET_ROOM_ACTIVE: '/api/active_rooms',
  API_ENTITY_ADMIN: '/api/admin_entity',
  API_SERVICE_LIST: '/api/item',
  API_DETAILS_ENTITY: '/api/entity/',
  API_SET_DEVICE_TOKEN: '/api/device',
  GET_USER_INFO: '/api/admin',
  GET_NUMBER_MY_REQUEST: '/api/statistics/my_requests',
  GET_NUMBER_ALL_REQUEST: '/api/statistics/all_requests',
  API_LOGOUT: '/api/logout',
};
